"""Week 21: honest, offline alignment and interpretability teaching contracts."""

from .interpretability import (
    ActivationMetrics,
    LinearProbe,
    SAETraining,
    TinySAE,
    activation_metrics,
    fit_linear_probe,
    logit_lens,
    probe_accuracy,
    probe_fixture,
    sae_fixture,
    sae_loss,
    train_sae,
)
from .preferences import (
    DPOReport,
    PreferenceBatch,
    TinyPolicy,
    dpo_loss,
    freeze_reference,
    preference_fixture,
    train_dpo,
)
from .safety import (
    MockTools,
    Response,
    SafetyCase,
    SafetyReport,
    SafetyResult,
    ToolDeniedError,
    ToolEvent,
    evaluate_red_team,
    fixture_assistant,
    red_team_fixture,
)

__all__ = [
    "ActivationMetrics",
    "DPOReport",
    "LinearProbe",
    "MockTools",
    "PreferenceBatch",
    "Response",
    "SAETraining",
    "SafetyCase",
    "SafetyReport",
    "SafetyResult",
    "TinyPolicy",
    "TinySAE",
    "ToolDeniedError",
    "ToolEvent",
    "activation_metrics",
    "dpo_loss",
    "evaluate_red_team",
    "fit_linear_probe",
    "fixture_assistant",
    "freeze_reference",
    "logit_lens",
    "preference_fixture",
    "probe_accuracy",
    "probe_fixture",
    "red_team_fixture",
    "sae_fixture",
    "sae_loss",
    "train_dpo",
    "train_sae",
]
